### ISSUE TITLE
locative ios-app no leave/exit state

### ISSUE THREAD

**Issue by mrhome7** [LocativeHQ/Locative-iOS#46]
Hi locative Team,
the locative app is doing a good Job on my iPhone 6. I used it with Geofancy module on FHEM.
But with iphone5 i only receive "enter" state of my "Fence".
I receive no Exit state of the Fence.
I have checked logs of my geofancy/fhem Server. Check Settings in locative app several times.
i dont see any mistake.

Maybe this could be a bug in the app?
Regards,
Markus

**Comment by kimar** [comment]
Hi, sounds like a bug indeed but as the whole process of Geofencing is handled by system APIs this will be hard to debug. Of course there's also a chance the app actually get's those events but drops them for some reason. I'd reckon without having some advanced debugging in place this will be close to impossible to oversee. Do you have a [Locative Web App](https://my.locative.io) account? This usually helps in debugging as it shows the result of HTTP requests which are being made by the app.

**Comment by mrhome7** [comment]
Hi Marcus,

I now The reason for my Problem. My phone doesn't have a mobile Connection when i leave my Home. Is it Possible to Cache The leave-home and reach-home request Till The Connection IS back. This would help to solve my Problem.

Regards,
Markus


Am 29.07.2016 um 09:02 schrieb Marcus Kida <notifications@github.com<mailto:notifications@github.com>>:


Hi, sounds like a bug indeed but as the whole process of Geofencing is handled by system APIs this will be hard to debug. Of course there's also a chance the app actually get's those events but drops them for some reason. I'd reckon without having some advanced debugging in place this will be close to impossible to oversee. Do you have a Locative Web App<https://my.locative.io> account? This usually helps in debugging as it shows the result of HTTP requests which are being made by the app.

-

**Comment by jsg4** [comment]
Hello, I am seeing this too. The fact that the network requested are not held until there is connectivity again is incredibly frustrating and doesn't work like an iOS app should. Is this something that can be fixed?

Also are you using actual geofencing API and setting a geofence based on the address entered, or using corelocation?

**Comment by kimar** [comment]
Hi @jsg4 this should already be the case: https://github.com/LocativeHQ/Locative-iOS/blob/master/Locative/Lib/HttpRequestManager.swift#L44

Also the app is using the Geofencing API's (which are part of CoreLocation) Geofences are always based off coordinates + radius: https://github.com/LocativeHQ/Locative-iOS/blob/master/Locative/Lib/GeofenceManager.m#L246

I'll have a look into this when I find some time.

**Comment by gbraux** [comment]
I confirm that there may be an issue / bug when locative triggers an action, but no network is available (no 3G nor Wifi) ... 
It looks like the success of the requests depends on the time to get a working network connection after an event is triggered. What I have experienced (but not formally validated) is that if you do not get data connectivity on your device in the next 15 minutes after an event, no GET/POST request will ever be send when you get connectivity back (app goes to sleep ?). 
But I noticed that ,at the next event (or next time you manually open the locative app), this old request may eventually be sent ...

**Comment by kimar** [comment]
This will be fixed together with https://github.com/LocativeHQ/Locative-iOS/issues/39 and/or https://github.com/LocativeHQ/Locative-iOS/issues/58
