### ISSUE TITLE
App close when trying to save beacon location

### ISSUE THREAD

**Issue by benzman81** [LocativeHQ/Locative-iOS#59]
On my iPhone 7 Plus iOS 10.2 I cannot use Licative anymore. Ibdid an uninstall and installed again. As soon as I want to save a beacon setup the app crashes and I cannot opennit again. Quits right away. Only reinstall brings me back to the app. Geofences work.

**Comment by kimar** [comment]
Confirmed there is an issue with this, unfortunately submission for the App Store are closed between 23/12 and 27/12 so a fix won't make it live before then.

**Comment by kimar** [comment]
@benzman81 the issue has been fixed and there's a beta available which contains this fix, if you'd like to participate in our beta program, please sign up at https://ios-beta.locative.io

Cheers,
Marcus

**Comment by benzman81** [comment]
Working in beta. Thx for the fix. Happy holidays.
