### ISSUE TITLE
iOS 3.1.4 delivers false HTTP webHook information

### ISSUE THREAD

**Issue by andipilz** [LocativeHQ/Locative-iOS#60]
Using FHEM and the Geofence-Module I receive the following log entry there:

2016.12.29 18:38:13 4: Connection accepted from WEBhook_192.168.1.4_59572
2016.12.29 18:38:13 4: WEBhook_192.168.nnn.nnn_59572 POST /webhook/geo&device=1AB31F4A-nnnn-nnnn-nnnn-nnnnnnnnnnnnnn&device_model=iPhone8%2C4&device_type=iPhone&latitude=48.nnnnnnnnnnnnnn&longitude=10. nnnnnnnnnnnnnn**×tamp**=1483033093&trigger=test; BUFLEN:0
2016.12.29 18:38:13 4: name: /webhook/geo&device=1AB31F4A-nnnn-nnnn-nnnn-nnnnnnnnnnnnnn&device_model=iPhone8%2C4&device_type=iPhone&latitude=48. nnnnnnnnnnnnnn&longitude=10. nnnnnnnnnnnnnn**×tamp**=1483033093&trigger=test / RL:63 / text/plain; charset=utf-8 / Content-Encoding: gzip
 /

This does not deliver an "id" but some strange entry "tamp" (in bold above) separated by and "x" which is actually no ex but a multiplied-by. I cannot track down, where this comes in.
I posted a similar entry to the FHEM forums, to be sure.

BR Andreas

**Comment by kimar** [comment]
Hi @andipilz, unfortunately I can't confirm this, both POST and GET requests in v3.1.3-3.1.5 send a correct payload e.g.:

```
{"device":"A2AA7237-6B05-4D65-BFA2-0A3CF055E6C8","device_model":"iPhone9,4","device_type":"iOS","id":"Home","latitude":"xx.xxx","longitude":"xx.xxx","timestamp":"xx.xxx","trigger":"enter"}
```

I'd assume there is an issue on the FHEM side deserializing the payload? Could you provide a link to your post in the FHEM forum?

P.s: [Here's a Slack Group](https://slack.locative.io) for Locative where we can more easily discuss such issues, I've set up a channel specifically for FHEM integrations there.

**Comment by andipilz** [comment]
Hi @kimar !

Have a good new one! ;-)

Here is the link to the FHEM forum article and I am checking on the Slack Group in a few minutes: https://forum.fhem.de/index.php/topic,63200.msg548843.html#msg548843
I almost didn't find it myself again, as it does not show up under my own messages ...

Gruß Andi

**Comment by andipilz** [comment]
Hi @kimar,

I posted an update to the FHEM forum: https://forum.fhem.de/index.php/topic,63200.msg554366.html#msg554366 reflecting the "mutilation" of POST requests by my reverse proxy under OS X 10.11, Server 5.0.4.

For here, I suggest to close the topic, once we have done the testing on the test request ID topic at SLACK.

Gruß Andi

**Comment by andipilz** [comment]
Tested well again with 3.1.7 (516). Closed.
