### ISSUE TITLE
Approximate iBeacon Distance threshold by rssi

### ISSUE THREAD

**Issue by JonSilver** [LocativeHQ/Locative-iOS#64]
If there are several iBeacons around the house, their ranges overlap. It should be possible to use rssi to approximate the distance to the iBeacon. A minimum distance threshold setting on Locative iBeacons would offer greater precision, possibly down to room level.

**Comment by kimar** [comment]
Hi @JonSilver infortunately this is not possible due to limitations on the `CLBeaconRegion` APIs, to limit the distance you need a beacon that's capable of changing the range. Estimote Beacons are (amongs others) capable of doing this: http://blog.estimote.com/post/74816977799/estimote-app-v1-2

**Comment by JonSilver** [comment]
Ah. Ok. It's just that Beecon+ by Ricardo Menezes appears to be able to do this per iBeacon with a simple minimum diatance setting of immediate, near or far.

![img_4379](https://cloud.githubusercontent.com/assets/8831106/21748651/c8326f88-d581-11e6-8606-e59ee2b170a2.PNG)
